[package]
name = "naom"
version = "0.1.0"
authors = ["Byron Houwens <zhion360@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.115"
merkletree = "0.21.0"
bincode = "1.3.1"
bytes = "0.5.6"
sodiumoxide = "0.2.6"
sha3 = "0.9.1"
crypto = "0.1.2"
tracing = "0.1.19"
colored = "2.0.0"
rocksdb = "0.15.0"
hex = "0.4.2"
rayon = "1.4.0"
