[package]
name = "naom"
version = "0.1.0"
authors = ["Byron Houwens <zhion360@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.115", features = ["derive"] }
bincode = "1.3.1"
bytes = "1.0.1"
sodiumoxide = "0.2.6"
sha3 = "0.9.1"
tracing = "0.1.19"
colored = { version = "2.0.0", optional = true }
rocksdb = { version = "0.15.0", optional = true }
hex = "0.4.2"
time = "0.2.25"
rand = "0.8.3"
merkle-log = "0.0.3"
actix-rt = "*"

[features]
default = []
build_bin = ["rocksdb", "colored"]

[[bin]]
name = "main"   
required-features = ["build_bin"]

