[package]
name = "naom"
version = "0.1.0"
authors = ["Byron Houwens <zhion360@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "*"
bincode = "1.3.1"
bytes = "1.0.1"
colored = { version = "2.0.0", optional = true }
hex = "0.4.2"
merkle-log = "0.0.3"
rand = "0.8.3"
ring = "0.16.20"
rocksdb = { version = "0.15.0", optional = true }
serde = { version = "1.0.115", features = ["derive"] }
serde-big-array = { version = "0.3.2", features = ["const-generics"] }
sha3 = "0.9.1"
time = "0.2.25"
tracing = "0.1.19"

[features]
default = []
build_bin = ["rocksdb", "colored"]

[[bin]]
name = "main"   
required-features = ["build_bin"]

